language: python
python:
  - "3.5.2"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run test
script:
  - python3 bancomat/manage.py test api
  - flask test models