# Generated by Django 2.1.1 on 2018-09-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('bill_count', models.IntegerField(default=0, verbose_name='колличество')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
